kind: Service
apiVersion: v1
metadata:
  namespace: nginx
  name: pod-service

spec:
  selector:
    app: nginx
  ports:
   - protocol: TCP
     port: 8080
     targetPort: 8080
     nodePort: 30003
  type: NodePort
